"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "./lib_supabase";
type M={id:string;nombre:string;costo_kg:number;activo:boolean};type P={id:string;nombre:string;costo_hora:number;potencia_w:number;activo:boolean};type Q={id:string;folio:string;cliente:string;pieza:string;material_id:string|null;impresora_id:string|null;peso_g:number;horas_impresion:number;costo_real:number;precio_venta:number;utilidad:number;estado:string;created_at:string};
const money=(n:number)=>n.toLocaleString("es-MX",{style:"currency",currency:"MXN"}),N=(x:any)=>Number(x)||0;
export default function Home(){
 const [user,setUser]=useState<any>(),[section,setSection]=useState("dashboard"),[m,setM]=useState<M[]>([]),[p,setP]=useState<P[]>([]),[q,setQ]=useState<Q[]>([]),[c,setC]=useState<any>({}),[msg,setMsg]=useState("");
 const [f,setF]=useState({cliente:"",pieza:"",material:"",printer:"",peso:100,horas:2,merma:10,labor:.5,otros:0});
 const load=async()=>{const [a,b,d,e]=await Promise.all([supabase.from("materiales_3d").select("*").order("nombre"),supabase.from("impresoras_3d").select("*").order("nombre"),supabase.from("cotizaciones_3d").select("*").order("created_at",{ascending:false}),supabase.from("configuracion_3d").select("*")]);setM(a.data||[]);setP(b.data||[]);setQ(d.data||[]);const x:any={};(e.data||[]).forEach((r:any)=>x[r.clave]=N(r.valor));setC(x)};
 useEffect(()=>{supabase.auth.getSession().then(x=>setUser(x.data.session?.user));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(user)load()},[user]);
 const calc=useMemo(()=>{const mm=m.find(x=>x.id===f.material),pp=p.find(x=>x.id===f.printer);const mat=N(f.peso)*(1+N(f.merma)/100)/1000*(mm?.costo_kg||0),mac=N(f.horas)*(pp?.costo_hora||0),ene=N(f.horas)*(pp?.potencia_w||0)/1000*(c.electricidad_kwh??3.2),lab=N(f.labor)*(c.mano_obra_hora??80),cost=mat+mac+ene+lab+N(f.otros),sale=Math.max(c.precio_minimo??80,cost*(1+(c.utilidad_pct??45)/100));return{mat,mac,ene,lab,cost,sale,util:sale-cost}},[f,m,p,c]);
 if(!user)return <Login/>;
 const save=async()=>{if(!f.pieza)return setMsg("Escribe el nombre de la pieza.");const num=(q.length?Math.max(...q.map(x=>N(x.folio.replace(/\D/g,"")))):0)+1;const row={folio:"C3D-"+String(num).padStart(5,"0"),cliente:f.cliente||"Mostrador",pieza:f.pieza,material_id:f.material||null,impresora_id:f.printer||null,peso_g:N(f.peso),horas_impresion:N(f.horas),merma_pct:N(f.merma),costo_material:calc.mat,costo_electricidad:calc.ene,costo_maquina:calc.mac,costo_mano_obra:calc.lab,otros_costos:N(f.otros),costo_real:calc.cost,precio_venta:calc.sale,utilidad:calc.util,estado:"Pendiente"};const {error}=await supabase.from("cotizaciones_3d").insert(row);setMsg(error?error.message:"Cotización guardada.");if(!error){await load();setSection("quotes")}};
 const nav=[["dashboard","Dashboard","⌂"],["quote","Nueva cotización","＋"],["quotes","Cotizaciones","▤"],["materials","Materiales","◈"],["printers","Impresoras","▣"],["settings","Configuración","⚙"]],title=nav.find(x=>x[0]===section)?.[1];
 return <main className="app"><aside className="sidebar"><div className="brand"><div className="brandMark">3D</div><div><b>Cotizador 3D</b><span>La Garra Estampa</span></div></div><div className="nav">{nav.map(x=><button key={x[0]} className={section===x[0]?"active":""} onClick={()=>setSection(x[0])}><span>{x[2]}</span>{x[1]}</button>)}</div><div className="sidebarFoot">{user.email}<br/><button onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></div></aside><section className="content"><header><div><div className="eyebrow">IMPRESIÓN 3D</div><h1>{title}</h1></div><button className="primary" onClick={()=>setSection("quote")}>＋ Nueva cotización</button></header>{msg&&<div className="notice" onClick={()=>setMsg("")}>{msg}</div>}{section==="dashboard"&&<Dashboard q={q} go={setSection}/>} {section==="quote"&&<Quote f={f} setF={setF} m={m} p={p} calc={calc} save={save}/>} {section==="quotes"&&<Quotes q={q} m={m} p={p} load={load} setMsg={setMsg}/>} {section==="materials"&&<Catalog kind="m" items={m} load={load} setMsg={setMsg}/>} {section==="printers"&&<Catalog kind="p" items={p} load={load} setMsg={setMsg}/>} {section==="settings"&&<Settings c={c} load={load} setMsg={setMsg}/>}</section></main>
}
function Login(){const [x,setX]=useState({email:"",password:""}),[e,setE]=useState("");return <main className="login"><div className="loginCard"><div className="brandMark big">3D</div><div className="eyebrow">LA GARRA ESTAMPA</div><h1>Cotizador 3D</h1><p>Inicia sesión con tu cuenta de Supabase.</p><form onSubmit={async ev=>{ev.preventDefault();const {error}=await supabase.auth.signInWithPassword(x);if(error)setE(error.message)}}><input type="email" placeholder="Correo" required value={x.email} onChange={ev=>setX({...x,email:ev.target.value})}/><input type="password" placeholder="Contraseña" required value={x.password} onChange={ev=>setX({...x,password:ev.target.value})}/><button className="primary full">Entrar</button></form>{e&&<div className="error">{e}</div>}</div></main>}
function Dashboard({q,go}:{q:Q[];go:(x:string)=>void}){const total=q.reduce((a,x)=>a+N(x.precio_venta),0);return <div className="page"><div className="stats"><Stat a="Cotizaciones" b={String(q.length)} c="histórico"/><Stat a="Pendientes" b={String(q.filter(x=>x.estado==="Pendiente").length)} c="por atender"/><Stat a="Venta cotizada" b={money(total)} c="acumulado"/><Stat a="Utilidad" b={money(q.reduce((a,x)=>a+N(x.utilidad),0))} c="estimada"/></div><div className="grid2"><Panel t="Acciones rápidas"><div className="quick"><button onClick={()=>go("quote")}><strong>＋</strong><span>Nueva cotización<small>Calcular una pieza</small></span></button><button onClick={()=>go("materials")}><strong>◈</strong><span>Materiales<small>Costos por kg</small></span></button><button onClick={()=>go("settings")}><strong>⚙</strong><span>Costos<small>Electricidad y mano de obra</small></span></button></div></Panel><Panel t="Últimas cotizaciones"><Table q={q.slice(0,6)}/></Panel></div></div>}
function Stat({a,b,c}:{a:string;b:string;c:string}){return <div className="stat"><span>{a}</span><b>{b}</b><small>{c}</small></div>}function Panel({t,children}:{t:string;children:any}){return <div className="panel"><div className="panelHead"><b>{t}</b></div>{children}</div>}
function Field({l,children}:{l:string;children:any}){return <label className="field"><span>{l}</span>{children}</label>}
function Quote({f,setF,m,p,calc,save}:{f:any;setF:any;m:M[];p:P[];calc:any;save:()=>void}){const h=(k:string)=>(e:any)=>setF({...f,[k]:e.target.type==="number"?N(e.target.value):e.target.value});return <div className="page"><div className="quoteLayout"><div className="panel formPanel"><div className="panelHead"><b>Datos de la pieza</b></div><div className="formGrid"><Field l="Cliente"><input value={f.cliente} onChange={h("cliente")} placeholder="Nombre"/></Field><Field l="Pieza"><input value={f.pieza} onChange={h("pieza")} placeholder="Nombre de pieza"/></Field><Field l="Material"><select value={f.material} onChange={h("material")}><option value="">Selecciona</option>{m.filter(x=>x.activo).map(x=><option key={x.id} value={x.id}>{x.nombre} · {money(x.costo_kg)}/kg</option>)}</select></Field><Field l="Impresora"><select value={f.printer} onChange={h("printer")}><option value="">Selecciona</option>{p.filter(x=>x.activo).map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></Field><Field l="Peso (g)"><input type="number" value={f.peso} onChange={h("peso")}/></Field><Field l="Tiempo (h)"><input type="number" step=".1" value={f.horas} onChange={h("horas")}/></Field><Field l="Merma (%)"><input type="number" value={f.merma} onChange={h("merma")}/></Field><Field l="Mano de obra (h)"><input type="number" step=".1" value={f.labor} onChange={h("labor")}/></Field><Field l="Otros costos"><input type="number" value={f.otros} onChange={h("otros")}/></Field></div></div><div className="panel summary"><div className="summaryTop"><span>PRECIO SUGERIDO</span><b>{money(calc.sale)}</b><small>Calculado automáticamente</small></div><Line a="Material" b={money(calc.mat)}/><Line a="Electricidad" b={money(calc.ene)}/><Line a="Máquina" b={money(calc.mac)}/><Line a="Mano de obra" b={money(calc.lab)}/><Line a="Otros" b={money(f.otros)}/><div className="totalLine"><span>Costo real</span><b>{money(calc.cost)}</b></div><div className="margin"><span>Utilidad</span><strong>{money(calc.util)}</strong></div><button className="primary full" onClick={save}>Guardar cotización</button></div></div></div>}
function Line({a,b}:{a:string;b:string}){return <div className="line"><span>{a}</span><b>{b}</b></div>}
function Table({q,m=[],p=[],del}:{q:Q[];m?:M[];p?:P[];del?:(id:string)=>void}){return q.length?<div className="table"><div className="tr th"><span>Folio</span><span>Cliente / pieza</span><span>Material</span><span>Precio</span><span>Estado</span></div>{q.map(x=><div className="tr" key={x.id}><span className="mono">{x.folio}</span><span><b>{x.cliente}</b><small>{x.pieza}</small></span><span>{m.find(z=>z.id===x.material_id)?.nombre||"—"}</span><span><b>{money(x.precio_venta)}</b></span><span><em>{x.estado}</em>{del&&<button className="dangerBtn" onClick={()=>del(x.id)}>×</button>}</span></div>)}</div>:<div className="empty">No hay cotizaciones.</div>}
function Quotes({q,m,p,load,setMsg}:{q:Q[];m:M[];p:P[];load:()=>Promise<void>;setMsg:(x:string)=>void}){const [s,setS]=useState("");const list=q.filter(x=>(x.folio+" "+x.cliente+" "+x.pieza).toLowerCase().includes(s.toLowerCase()));const del=async(id:string)=>{if(!confirm("¿Eliminar cotización?"))return;const {error}=await supabase.from("cotizaciones_3d").delete().eq("id",id);setMsg(error?error.message:"Cotización eliminada.");if(!error)load()};return <div className="page"><div className="panel"><div className="panelHead"><b>Historial</b></div><div style={{padding:"14px 20px"}}><input style={{width:"100%",padding:11,border:"1px solid #dfe3e8",borderRadius:8}} placeholder="Buscar…" value={s} onChange={e=>setS(e.target.value)}/></div><Table q={list} m={m} p={p} del={del}/></div></div>}
function Catalog({kind,items,load,setMsg}:{kind:"m"|"p";items:any[];load:()=>Promise<void>;setMsg:(x:string)=>void}){const [x,setX]=useState<any>(kind==="m"?{nombre:"",costo_kg:420}:{nombre:"",costo_hora:12,potencia_w:150});const save=async()=>{const table=kind==="m"?"materiales_3d":"impresoras_3d",row=kind==="m"?{nombre:x.nombre,costo_kg:N(x.costo_kg),activo:true}:{nombre:x.nombre,costo_hora:N(x.costo_hora),potencia_w:N(x.potencia_w),activo:true};const {error}=await supabase.from(table).insert(row);setMsg(error?error.message:"Agregado.");if(!error)load()};return <div className="page"><div className="panel"><div className="panelHead"><b>{kind==="m"?"Materiales":"Impresoras"}</b></div><div className="formGrid"><Field l="Nombre"><input value={x.nombre} onChange={e=>setX({...x,nombre:e.target.value})}/></Field>{kind==="m"?<Field l="Costo $/kg"><input type="number" value={x.costo_kg} onChange={e=>setX({...x,costo_kg:N(e.target.value)})}/></Field>:<><Field l="Costo $/hora"><input type="number" value={x.costo_hora} onChange={e=>setX({...x,costo_hora:N(e.target.value)})}/></Field><Field l="Potencia W"><input type="number" value={x.potencia_w} onChange={e=>setX({...x,potencia_w:N(e.target.value)})}/></Field></>}</div><button className="primary" style={{margin:"0 22px 15px"}} onClick={save}>Agregar</button><div className="catalog">{items.map((z,i)=><div className="catalogItem" key={z.id}><div className="avatar">{i+1}</div><div><b>{z.nombre}</b><small>{kind==="m"?money(z.costo_kg)+" / kg":money(z.costo_hora)+" / h · "+z.potencia_w+" W"}</small></div></div>)}</div></div></div>}
function Settings({c,load,setMsg}:{c:any;load:()=>Promise<void>;setMsg:(x:string)=>void}){const [v,setV]=useState({electricidad_kwh:c.electricidad_kwh??3.2,mano_obra_hora:c.mano_obra_hora??80,utilidad_pct:c.utilidad_pct??45,precio_minimo:c.precio_minimo??80});useEffect(()=>setV({electricidad_kwh:c.electricidad_kwh??3.2,mano_obra_hora:c.mano_obra_hora??80,utilidad_pct:c.utilidad_pct??45,precio_minimo:c.precio_minimo??80}),[c]);const save=async()=>{for(const [clave,valor] of Object.entries(v))await supabase.from("configuracion_3d").upsert({clave,valor:N(valor)},{onConflict:"clave"});setMsg("Configuración guardada.");load()};return <div className="page"><div className="panel settings"><div className="panelHead"><b>Parámetros de costeo</b></div><div className="formGrid">{Object.entries(v).map(([k,val])=><Field key={k} l={k}><input type="number" step=".01" value={val as any} onChange={e=>setV({...v,[k]:N(e.target.value)})}/></Field>)}</div><button className="primary" style={{margin:"0 22px 22px"}} onClick={save}>Guardar configuración</button></div></div>}
